/**:
  ros__parameters:

    # ----- Robot description -----
    urdf_package: "ur_description"
    robot_type: "ur10e"

    # ----- Cinematica -----
    end_effector_frame: "tool0"
    base_frame: "base_link"

    # ----- Topics -----
    joint_states_topic: "/joint_states"
    fk_pose_topic: "/fk_pose"