/**:
  ros__parameters:

    # ----- Robot description -----
    urdf_package: "franka_description"
    robot_type: "fr3"

    # ----- Cinematica -----
    end_effector_frame: "fr3_hand_tcp"
    base_frame: "fr3_link0"

    # ----- Topics -----
    joint_states_topic: "/joint_states"
    fk_pose_topic: "/fk_pose"
