# config/ur10e_params.yaml
/generic_ik_node: # Questo deve corrispondere al nome del nodo nel launch file
  ros__parameters:
    robot_description_package: "ur_description"
    urdf_xacro_path_relative: "urdf/ur.urdf.xacro"
    mesh_dir_path_relative: "meshes"
    robot_type: "ur10e" # Utilizzato dal tuo nodo nel comando xacro
    robot_name: "ur10e" # Utilizzato dal tuo nodo per i file temporanei
    end_effector_frame: "tool0"
    controller_command_topic: "/forward_position_controller/commands"
    controllable_joint_names:
      - "shoulder_pan_joint"
      - "shoulder_lift_joint"
      - "elbow_joint"
      - "wrist_1_joint"
      - "wrist_2_joint"
      - "wrist_3_joint"
    ik_tolerance: 1.0e-4
    ik_max_iter: 4000
    ik_dt: 0.1
    ik_damping: 0.05


